version: 2

sphinx:
  builder: html
  configuration: doc/conf.py
  
python:
  version: 3.6
  install:
    - requirements: 'requirements.txt'
    - requirements: 'doc/requirements.txt'
    - method: setuptools
      path: './'
