dist: bionic
language: python

python:
- '3.6'
- '3.7'
- '3.8'

stages:
- lint
- test
- deploy

env:
  matrix:
  - DJANGO_VERSION=2.2.*
  - DJANGO_VERSION=3.0.*
  - DJANGO_VERSION=dev

install:
- pip install .[dev]
- pip install codecov coverage
- if [[ $DJANGO_VERSION == dev ]]; then pip install -e git+https://github.com/django/django@master#egg=django
  -U; else pip install Django==$DJANGO_VERSION -U; fi

script:
- coverage run --source=template_engines ./manage.py test

after_success:
- codecov

jobs:
  allow_failures:
  - env: DJANGO_VERSION=dev

  include:
  - stage: lint
    install:
    - pip3 install flake8
    before_script: skip
    script:
    - flake8 template_engines
    after_success: skip

  - stage: deploy
    before_install: skip
    install: skip
    before_script: skip
    script: skip
    after_script: skip
    deploy:
      provider: pypi
      username: __token__
      password:
        secure: VK+W+bZdrOWf7OwvWGwVDnRdZgF2456RM1iqVyTf18Rzra2cL55EHW7g3BQLy4fZu5liQB0HnOnF20XvrGesfF1YqRBciZiqNTFONzfGx5p/LSkCobCPQLh7sZ054IRNbWRKVXb4Uz7YnXfjJefKuaLc9jFqq6mNLJd1L5IvignZYmhGHSXFKI5gNmGeM8tg+YL/NFhqCHEuvAFDeT68R7z3wg/Xp+8OHu2deVzdn/iP4iVvvyBg3++IEwCqSH7RKiAuHerTVeUU9rjdcPRaLv1S0dB4efCPk57vzsuM0rM1bVTd0YXnMqJ6QuB6Cwxc42r5tO6uaJ/IF2JuAIKXY/jNceSUc1iQeoO0PL32+rQgrWmsd/nog3rLFeIVRbNayo7N+C/H5z8SvcXPqRUaasU/Gdn7sNdAVjl2aUdoSgn6D2yNBvfCdp7hpRqedBs2w4YwH8gs5FRWudtcwKYzK6Yadv8Weys6wYmvcvEaU284YSe7h4k6kPtPiQOPgDBNhBF2mGlvh0wxImk5rl4bo+Fy2/LvnhcCxn7nJpmzBpy8HYNVZUjGLi5tG+kACx4BR/YPw6ZlsNDTuSVVGV9xysi8Sn2FkYm49KCsNRJs1wcNNhl877S8n5vnZRSUeurymwUFedSFJv8Ym3UEPnvUGIyFdGG7ouDoSgED2CIqYkE=
      on:
        tags: true
